// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVLIszUyUeRTU73tAHGU1oEMA9dCzI8zY',
    appId: '1:295964765669:web:6adaa7a66ea451753dd30c',
    messagingSenderId: '295964765669',
    projectId: 'dubucket-deb73',
    authDomain: 'dubucket-deb73.firebaseapp.com',
    storageBucket: 'dubucket-deb73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo3C5TPJHkgO5q8RIVnLCa7-BNHNNtNT8',
    appId: '1:295964765669:android:3b1615a9567eef443dd30c',
    messagingSenderId: '295964765669',
    projectId: 'dubucket-deb73',
    storageBucket: 'dubucket-deb73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54Cueug8NeeupDMiR2yGJnGnmkavPCvU',
    appId: '1:295964765669:ios:7372fce4c30faa663dd30c',
    messagingSenderId: '295964765669',
    projectId: 'dubucket-deb73',
    storageBucket: 'dubucket-deb73.appspot.com',
    androidClientId: '295964765669-fgv24k8rm4gl6o8nbnr0kp1qig2i30dp.apps.googleusercontent.com',
    iosClientId: '295964765669-4h1s9l4bplkrbo2lt09lu19p50uf2e96.apps.googleusercontent.com',
    iosBundleId: 'com.dubucket',
  );
}
